function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "untitled"};
	this.sidHashMap["untitled"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "untitled:1"};
	this.sidHashMap["untitled:1"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "untitled:1"};
	this.sidHashMap["untitled:1"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<Root>/Lamp"] = {sid: "untitled:11"};
	this.sidHashMap["untitled:11"] = {rtwname: "<Root>/Lamp"};
	this.rtwnameHashMap["<Root>/Lamp1"] = {sid: "untitled:12"};
	this.sidHashMap["untitled:12"] = {rtwname: "<Root>/Lamp1"};
	this.rtwnameHashMap["<Root>/Lamp2"] = {sid: "untitled:13"};
	this.sidHashMap["untitled:13"] = {rtwname: "<Root>/Lamp2"};
	this.rtwnameHashMap["<Root>/Output"] = {sid: "untitled:15"};
	this.sidHashMap["untitled:15"] = {rtwname: "<Root>/Output"};
	this.rtwnameHashMap["<Root>/Output1"] = {sid: "untitled:16"};
	this.sidHashMap["untitled:16"] = {rtwname: "<Root>/Output1"};
	this.rtwnameHashMap["<Root>/Output2"] = {sid: "untitled:17"};
	this.sidHashMap["untitled:17"] = {rtwname: "<Root>/Output2"};
	this.rtwnameHashMap["<S1>:4"] = {sid: "untitled:1:4"};
	this.sidHashMap["untitled:1:4"] = {rtwname: "<S1>:4"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "untitled:1:1"};
	this.sidHashMap["untitled:1:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:3"] = {sid: "untitled:1:3"};
	this.sidHashMap["untitled:1:3"] = {rtwname: "<S1>:3"};
	this.rtwnameHashMap["<S1>:2"] = {sid: "untitled:1:2"};
	this.sidHashMap["untitled:1:2"] = {rtwname: "<S1>:2"};
	this.rtwnameHashMap["<S1>:5"] = {sid: "untitled:1:5"};
	this.sidHashMap["untitled:1:5"] = {rtwname: "<S1>:5"};
	this.rtwnameHashMap["<S1>:9"] = {sid: "untitled:1:9"};
	this.sidHashMap["untitled:1:9"] = {rtwname: "<S1>:9"};
	this.rtwnameHashMap["<S1>:8"] = {sid: "untitled:1:8"};
	this.sidHashMap["untitled:1:8"] = {rtwname: "<S1>:8"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
